### ISSUE TITLE
EventHubs fails to build with 3.0 preview7 SDK

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7151]
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a
```

```
> dotnet build eng\service.proj

Core\ChannelEnumerableSubscription.cs(113,50): error CS8425: Async-iterator 'ChannelEnumerableSubscription<T>.EnumerateChannel(ChannelReader<T>, TimeSpan?, CancellationToken)' has one or more parameters of type 'CancellationToken' but none of them is decorated with the 'EnumeratorCancellation' attribute, so the cancellation token parameter from the generated 'IAsyncEnumerable<>.GetAsyncEnumerator' will be unconsumed [D:\github\azure\azure-sdk-for-net2\sdk\eventhub\Azure.Messaging.EventHubs\src\Azure.Messaging.EventHubs.csproj]
```
