### PR TITLE
Updated STG 100 changelogs to clarify overload changes

### LINKED ISSUE #55390: [BUG] Breaking change on DataLakeFileSystemClient.GetPaths not documented in changelog
### Library name and version

Azure.Storage.Files.DataLake 12.25.0

### Describe the bug

Hi
Found out that a breaking change on DataLakeFileSystemClient.GetPaths from Azure.Storage.Files.DataLake version 12.25.0, about the signature change from accepting `string path` as the first parameter to `DataLakeGetPathsOptions options`, it's not documented on the CHANGELOG.md file.

### Expected behavior

Instancing a DataLakeFileSystemClient from a DatalakeServiceClient, and trying to call GetPaths("my_path_string"), like previous versions.

### Actual behavior

The only GetPaths method overload only accepts `DataLakeGetPathsOptions options`

### Reproduction Steps

Instancing a DataLakeFileSystemClient from a DatalakeServiceClient, and trying to call GetPaths("my_path_string"), like previous versions.

### Environment

_No response_

### LINKED ISSUE #55418: [BUG] Breaking Change in Azure.Storage.Blobs 12.27.0: GetBlobsAsync parameters without default values
### Library name and version

Azure.Storage.Blobs 12.27.0

### Describe the bug

After upgrading from Azure.Storage.Blobs 12.26.0 to 12.27.0, code that previously compiled now fails with error CS7036, indicating that the `traits` parameter is required despite the documentation showing it should have a default value.

### Library Version
- **Package**: Azure.Storage.Blobs
- **Previous working version**: 12.26.0
- **Broken version**: 12.27.0
- **Target Framework**: net10.0

This change doesn't seems to be documented in the Changelog.md file.

### Expected behavior

The method signature should have default values for all parameters like previous version:

```csharp
public virtual AsyncPageable<BlobItem> GetBlobsAsync(
    BlobTraits traits = BlobTraits.None,
    BlobStates states = BlobStates.None,
    string prefix = default,
    CancellationToken cancellationToken = default)
```

### Actual behavior

error CS7036: There is no argument given that corresponds to the required parameter 'traits' of 'BlobContainerClient.GetBlobsAsync(BlobTraits, BlobStates, string, CancellationToken)'

### Reproduction Steps

Instantiate a BlobContainerClient and use GetBlobsAsync with these parameters.
_blobContainerClient.GetBlobsAsync(prefix: prefix, cancellationToken: cancellationToken);

### Environment

_No response_

### PR DESCRIPTION
**Pull request by seanmcc-msft**
Resolves https://github.com/Azure/azure-sdk-for-net/issues/55418
Resolves https://github.com/Azure/azure-sdk-for-net/issues/55390

### CODE REVIEW

**Review by nickliu-msft — APPROVED** [review]

**Review by nickliu-msft — APPROVED** [review]

**Comment by knd775** [comment]
Is Microsoft's stance that breaking changes on minor point releases are okay?

**Comment by jeremyhanoun** [comment]
Wow... So if a breaking change is documented on minor version then it becomes ok ?

**Comment by perlun** [comment]
I agree, making hard breaking changes in a minor version is unexpected.

In case this helps anyone, here (from "Go to definition" in Rider, when using the old version of the package reference) is the implementation of the old `GetBlobsAsync()` implementation from `12.25.0`, suggesting that suitable values for the `traits` and `states` would be `BlobTraits.None` and `BlobStates.None` if you have previously not been providing these parameters.

```c#
  public virtual AsyncPageable<BlobItem> GetBlobsAsync(
    BlobTraits traits = BlobTraits.None,
    BlobStates states = BlobStates.None,
    string prefix = null,
    CancellationToken cancellationToken = default (CancellationToken))
  {
    return new GetBlobsAsyncCollection(this, traits, states, prefix).ToAsyncCollection(cancellationToken);
  }
```
