### PR TITLE
Fix ShareLink sample to be able to build again

### PR DESCRIPTION
**Pull request by heaths**
Relates to #21074

### CODE REVIEW

**Comment by pakrym** [comment]
Should we add it to CI in some way?

**Comment by heaths** [comment]
It's a good idea. I'm actually not sure why, though I suspect it's because of `<IsPackable>false</IsPackable>`. I'll generate a binary log and figure out why it's not. Key Vault Proxy (in the sdk/keyvault/samples directory) builds during CIs.

**Comment by heaths** [comment]
I made sure that the getcert and sharelink samples could be copied out (sharelink via the custom `CopySource` target that copies linked sources) and built independently, so they should work once published to and downloaded from the Samples Browser.

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
We really need a better, shared solution for samples. This took a lot of know-how which I'm pretty sure partner teams won't have.

**Comment by Jinnanms** [comment]
I download sharelink.zip and extract it, but build in vs code, error is:
...\ShareLink\Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttributeAttribute' does not exist in the namespace 'Azure.Core' (are you missing an assembly reference?) 

can anyone give me some idea? thanks

**Comment by heaths** [comment]
Did you run `dotnet restore` on the project? Also, please open a separate issue if this doesn't work. Replying on an unrelated closed issue may not always get noticed.
